# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "repository", " BankServiceLayer " ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore BankBackend/BankBackend.sln
    - name: Build
      run: dotnet build BankBackend/BankBackend.sln --no-restore
    - name: Test
      run: dotnet test BankBackend/BankBackend.sln --no-build --verbosity normal
